### ISSUE TITLE
Nested comment padding and positioning

### ISSUE THREAD

**Issue by gadenbuie** [quarto-ext/bluesky-comments#21]
Nested comments should be left aligned so the border is even with the parent post

![image](https://github.com/user-attachments/assets/f6f539c6-32c9-4df0-b506-c795f1d53411)

And the indentation lines should all end at the same line (without bottom padding)

![image](https://github.com/user-attachments/assets/24d78c39-a06d-4060-ba72-94e38f835ae2)

**Comment by coatless** [comment]
So, if we take reddit for instance:

https://www.reddit.com/r/news/comments/1heb7j9/drone_sighting_temporarily_shuts_down_runways_at/ 

The alignment here seems to be underneath the upvote icon itself with the avatar a smidge to the left.

<img width="747" alt="Reddit screenshot of nested comments" src="https://github.com/user-attachments/assets/f1ff268b-8937-45ab-a2a4-0e0f4e8ca1f3" />
