### ISSUE TITLE
Author name and handle wrapping

### ISSUE THREAD

**Issue by gadenbuie** [quarto-ext/bluesky-comments#22]
I think we could do a little better here with a couple of CSS tweaks.

![image](https://github.com/user-attachments/assets/888e3d8b-a314-43b5-80dc-2e62e927582b)

**Comment by coatless** [comment]
I'm thinking it might be better to just show the `@user` instead of the person's name or move the username underneath the real name? 

Or can you mention a bit more about the tweaks we want here?

**Comment by gadenbuie** [comment]
I was thinking we could have the handle below the display name if there's not enough space. But looking at this again we could just show one name, preferring the display name.

**Comment by coatless** [comment]
Let's simplify and just opt to show the username.

I'll tackle this later tonight.

**Comment by gadenbuie** [comment]
> Let's simplify and just opt to show the username.

Personally, I think the display name looks better (the second post in the screenshot), but in the case of the first post where there is no display name (or it's the same as the handle), it's be better to show the handle with the `@`.
